FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY AzureBrasilCloudVaga.Web.csproj .
RUN dotnet restore AzureBrasilCloudVaga.Web.csproj
COPY . .


FROM build AS publish
RUN dotnet publish AzureBrasilCloudVaga.Web.csproj -c Release -o /app/publish


FROM nginx:alpine AS final
WORKDIR /usr/share/nginx/html
RUN apk add jq
COPY script.sh /docker-entrypoint.d/40-script.sh
RUN sed -i 's/\r$//' /docker-entrypoint.d/40-script.sh
RUN chmod +x /docker-entrypoint.d/40-script.sh

COPY --from=publish /app/publish/wwwroot .
COPY nginx.conf /etc/nginx/nginx.conf